apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGO_URI: "mongodb://mongo:27017/videos"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"